datasets:
  type: FTGANDataset
  train:
    split: auto
    font_dir: &font_dir ./data/ftgan-fonts
    test_unknown_content: &test_unknown_content True
    imsize: 64
    reference_imgs:
      replace: False
      char: &reference_char 1
      style: &reference_style 6

    squeeze_gray: True
    transform:
    # TODO

    # loader configs
    shuffle: True
    batch_size: 64
    num_workers: 8

  eval:
    split: auto
    font_dir: *font_dir
    test_unknown_content: *test_unknown_content
    imsize: 64
    reference_imgs:
      replace: False
      char: *reference_char
      style: *reference_style

    squeeze_gray: True
    transform:
    # TODO

    # loader configs
    shuffle: True
    batch_size: 16
    num_workers: 4
