datasets:
  type: GoogleFontDataset
  train:
    split: auto
    font_dir: &font_dir ../DATA/fonts-image-20230929
    imsize: 64
    reference_imgs:
      replace: False
      char: &reference_char 1
      style: &reference_style 5

    squeeze_gray: &squeeze_gray True
    transform:
    # TODO

    # loader configs
    shuffle: True
    batch_size: 64
    num_workers: 12

  eval:
    split: auto
    font_dir: *font_dir
    imsize: 64
    reference_imgs:
      replace: False
      char: *reference_char
      style: *reference_style

    squeeze_gray: *squeeze_gray
    transform:
    # TODO

    # loader configs
    shuffle: True
    batch_size: 1
    num_workers: 4
