datasets:
  type: GoogleFontDataset
  train:
    split: auto

    imsize: 64
    reference_imgs:
      replace: False
      char: 1
      style: 5

    squeeze_gray: True
    transform:
    # TODO

    # loader configs
    shuffle: True
    batch_size: 64
    num_workers: 8

  eval:
    split: auto

    imsize: 64
    reference_imgs:
      replace: False
      char: 1
      style: 5

    squeeze_gray: True
    transform:
    # TODO

    # loader configs
    shuffle: True
    batch_size: 1
    num_workers: 4
