pl_config:
  checkpoint:
    callback:
      save_top_k: -1
      verbose: True
      every_n_epochs: 5 #epochs

  trainer:
    gradient_clip_val: 0
    max_epochs: 2000
    num_sanity_val_steps: 1
    fast_dev_run: False
    check_val_every_n_epoch: 5
    # distributed_backend: 'ddp'
    accelerator: 'cuda'
    benchmark: True