logging:
  dry_run: False
  device: cuda
  log_dir: /DATA1/hksong/logs/font
  seed: google-font-patch-full
  freq:
    train: 100 # step

  nepochs: 100
  nepochs_decay: 100

  gan_loss: lsgan
  lambda_L1: 100
  lambda_classifier: ~

  trainer: base

  savefiles: [
      '*.py',
      'data/*.*',
      'datasets/*.*',
      'models/*.*',
      'configs/*.*',
      'utils/*.*',
      'trainer/*.*',
  ]
